#!/bin/sh
#
# The remote-host testbed's one command. `up` builds and starts the fleet,
# mints the client key it logs in with, and writes testbed.sshconfig — the
# aliases the app's [[host]] blocks point at. `down` stops it; `status`
# asks every persona whether it answers.
#
#   ./testbed.sh up
#   ./testbed.sh status
#   ./testbed.sh down
#
# One manual step, once: add this line at the TOP of ~/.ssh/config (Include
# is global only before the first Host block), so the app's ssh sees the
# aliases. Remove the line and the testbed is gone without a trace.
#
#   Include <this directory>/testbed.sshconfig
#
set -e
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

ALIASES="plain old-tmux tmux35 no-tmux password-only max-sessions slow-banner alpine"
port_for() {
    case "$1" in
        plain) echo 2210 ;;
        old-tmux) echo 2211 ;;
        tmux35) echo 2212 ;;
        no-tmux) echo 2213 ;;
        password-only) echo 2214 ;;
        max-sessions) echo 2215 ;;
        slow-banner) echo 2216 ;;
        alpine) echo 2217 ;;
    esac
}

write_sshconfig() {
    {
        echo "# Generated by testbed.sh — aliases for the attache remote-host testbed."
        echo "# Paths are absolute to this checkout; regenerate with ./testbed.sh up."
        for alias in $ALIASES; do
            echo ""
            echo "Host attache-test-$alias"
            echo "  HostName 127.0.0.1"
            echo "  Port $(port_for "$alias")"
            echo "  User attache"
            echo "  IdentityFile $ROOT/keys/id_ed25519"
            echo "  IdentitiesOnly yes"
            echo "  UserKnownHostsFile $ROOT/keys/known_hosts"
            echo "  StrictHostKeyChecking accept-new"
        done
    } > "$ROOT/testbed.sshconfig"
}

case "${1:-}" in
up)
    mkdir -p keys
    [ -f keys/id_ed25519 ] || ssh-keygen -t ed25519 -N "" -C attache-testbed -f keys/id_ed25519
    # Recreated containers mint new host keys, and a *changed* key is a hard
    # ssh error accept-new does not cover. Starting clean every `up` trades
    # one TOFU accept per container for never hitting that wall.
    : > keys/known_hosts
    docker compose up -d --build
    write_sshconfig
    echo ""
    echo "Testbed is up. If ~/.ssh/config does not Include it yet, add this line at the TOP:"
    echo ""
    echo "  Include $ROOT/testbed.sshconfig"
    echo ""
    echo "Then add hosts in the app with these ssh destinations:"
    for alias in $ALIASES; do echo "  attache-test-$alias"; done
    ;;
down)
    docker compose down
    ;;
status)
    docker compose ps
    echo ""
    for alias in $ALIASES; do
        if ssh -F "$ROOT/testbed.sshconfig" -o BatchMode=yes -o ConnectTimeout=5 \
            "attache-test-$alias" true 2>/dev/null; then
            echo "attache-test-$alias: ssh ok"
        elif [ "$alias" = "password-only" ]; then
            echo "attache-test-$alias: refuses keys (that is its persona)"
        else
            echo "attache-test-$alias: NOT answering"
        fi
    done
    ;;
*)
    echo "usage: $0 up|down|status" >&2
    exit 64
    ;;
esac
